language: python

cache: pip

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

install:
  - pip install -r requirements.txt
  - pip install .
script: 
  - pytest ./tests/testsuite.py
